# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: ë¬¸ì„œ ë°°í¬

on:
  # "main" ë¸Œëœì¹˜ì— í‘¸ì‹œí•  ë•Œ ë§ˆë‹¤ ì›Œí¬í”Œë¡œìš° ì‘ë™
  push:
    branches: [ "main" ]

# GitHub Pages ì— ë°°í¬í•˜ê¸° ìœ„í•œ GITHUB_TOKEN ê¶Œí•œ ì„¤ì •
permissions:
  contents: read
  pages: write
  id-token: write
  
# ë™ì‹œì„± ë°°í¬ í—ˆìš©
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: macos-15  #ìµœì‹ ë²„ì „
    environment:
      # GitHub Pages ë¡œ ë°°í¬í•˜ê¸° ìœ„í•œ í•„ìˆ˜ ì„¤ì •
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: ì²´í¬ì•„ì›ƒ ğŸ›ï¸
      uses: actions/checkout@v4
      with:
        submodules: false
        fetch-depth: 1
        clean: true
    - name: (option) ì›Œí¬ìŠ¤í˜ì´ìŠ¤ë¥¼ safe.directoryë¡œ ì§€ì •
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1 # xcode ë²„ì „ ì„¤ì •ì„ ìœ„í•¨
      with:
        xcode-version: '16.4'
    - name: DocC ë¬¸ì„œ ë¹Œë“œ
      run: |
        chmod +x ./GENERATE_DOCS.sh
        ./GENERATE_DOCS.sh
    - name: artifact ì—…ë¡œë“œ
      uses: actions/upload-pages-artifact@v3
      with:
        # docs ê²½ë¡œì— ìˆëŠ” ê²ƒë§Œ ì—…ë¡œë“œ
        path: ./docs
    - name: GitHub Pages ì— ë°°í¬
      id: deployment
      uses: actions/deploy-pages@v4
